// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/book.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Book with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Book) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Book with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BookMultiError, or nil if none found.
func (m *Book) ValidateAll() error {
	return m.validate(true)
}

func (m *Book) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Year

	// no validation rules for Genre

	if len(errors) > 0 {
		return BookMultiError(errors)
	}

	return nil
}

// BookMultiError is an error wrapping multiple validation errors returned by
// Book.ValidateAll() if the designated constraints aren't met.
type BookMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookMultiError) AllErrors() []error { return m }

// BookValidationError is the validation error returned by Book.Validate if the
// designated constraints aren't met.
type BookValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookValidationError) ErrorName() string { return "BookValidationError" }

// Error satisfies the builtin error interface
func (e BookValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBook.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookValidationError{}

// Validate checks the field values on BookGetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BookGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookGetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BookGetRequestMultiError,
// or nil if none found.
func (m *BookGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BookGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := len(m.GetBookId()); l < 1 || l > 10 {
		err := BookGetRequestValidationError{
			field:  "BookId",
			reason: "value must contain between 1 and 10 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	_BookGetRequest_BookId_Unique := make(map[int64]struct{}, len(m.GetBookId()))

	for idx, item := range m.GetBookId() {
		_, _ = idx, item

		if _, exists := _BookGetRequest_BookId_Unique[item]; exists {
			err := BookGetRequestValidationError{
				field:  fmt.Sprintf("BookId[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_BookGetRequest_BookId_Unique[item] = struct{}{}
		}

		if item < 1 {
			err := BookGetRequestValidationError{
				field:  fmt.Sprintf("BookId[%v]", idx),
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return BookGetRequestMultiError(errors)
	}

	return nil
}

// BookGetRequestMultiError is an error wrapping multiple validation errors
// returned by BookGetRequest.ValidateAll() if the designated constraints
// aren't met.
type BookGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookGetRequestMultiError) AllErrors() []error { return m }

// BookGetRequestValidationError is the validation error returned by
// BookGetRequest.Validate if the designated constraints aren't met.
type BookGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookGetRequestValidationError) ErrorName() string { return "BookGetRequestValidationError" }

// Error satisfies the builtin error interface
func (e BookGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookGetRequestValidationError{}

// Validate checks the field values on BookAddRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BookAddRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookAddRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BookAddRequestMultiError,
// or nil if none found.
func (m *BookAddRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BookAddRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTitle()); l < 2 || l > 128 {
		err := BookAddRequestValidationError{
			field:  "Title",
			reason: "value length must be between 2 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 2 {
		err := BookAddRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 2 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetYear() < 1 {
		err := BookAddRequestValidationError{
			field:  "Year",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetGenre()) < 2 {
		err := BookAddRequestValidationError{
			field:  "Genre",
			reason: "value length must be at least 2 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BookAddRequestMultiError(errors)
	}

	return nil
}

// BookAddRequestMultiError is an error wrapping multiple validation errors
// returned by BookAddRequest.ValidateAll() if the designated constraints
// aren't met.
type BookAddRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookAddRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookAddRequestMultiError) AllErrors() []error { return m }

// BookAddRequestValidationError is the validation error returned by
// BookAddRequest.Validate if the designated constraints aren't met.
type BookAddRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookAddRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookAddRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookAddRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookAddRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookAddRequestValidationError) ErrorName() string { return "BookAddRequestValidationError" }

// Error satisfies the builtin error interface
func (e BookAddRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookAddRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookAddRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookAddRequestValidationError{}

// Validate checks the field values on BookListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BookListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BookListRequestMultiError, or nil if none found.
func (m *BookListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BookListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPagination() == nil {
		err := BookListRequestValidationError{
			field:  "Pagination",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookListRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookListRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookListRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BookListRequestMultiError(errors)
	}

	return nil
}

// BookListRequestMultiError is an error wrapping multiple validation errors
// returned by BookListRequest.ValidateAll() if the designated constraints
// aren't met.
type BookListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookListRequestMultiError) AllErrors() []error { return m }

// BookListRequestValidationError is the validation error returned by
// BookListRequest.Validate if the designated constraints aren't met.
type BookListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookListRequestValidationError) ErrorName() string { return "BookListRequestValidationError" }

// Error satisfies the builtin error interface
func (e BookListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookListRequestValidationError{}

// Validate checks the field values on BooksResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BooksResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BooksResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BooksResponseMultiError, or
// nil if none found.
func (m *BooksResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BooksResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBook() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BooksResponseValidationError{
						field:  fmt.Sprintf("Book[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BooksResponseValidationError{
						field:  fmt.Sprintf("Book[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BooksResponseValidationError{
					field:  fmt.Sprintf("Book[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BooksResponseMultiError(errors)
	}

	return nil
}

// BooksResponseMultiError is an error wrapping multiple validation errors
// returned by BooksResponse.ValidateAll() if the designated constraints
// aren't met.
type BooksResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BooksResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BooksResponseMultiError) AllErrors() []error { return m }

// BooksResponseValidationError is the validation error returned by
// BooksResponse.Validate if the designated constraints aren't met.
type BooksResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BooksResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BooksResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BooksResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BooksResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BooksResponseValidationError) ErrorName() string { return "BooksResponseValidationError" }

// Error satisfies the builtin error interface
func (e BooksResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBooksResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BooksResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BooksResponseValidationError{}

// Validate checks the field values on BookListResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BookListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BookListResponseMultiError, or nil if none found.
func (m *BookListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BookListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookListResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookListResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookListResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetBooks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BookListResponseValidationError{
						field:  fmt.Sprintf("Books[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BookListResponseValidationError{
						field:  fmt.Sprintf("Books[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BookListResponseValidationError{
					field:  fmt.Sprintf("Books[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BookListResponseMultiError(errors)
	}

	return nil
}

// BookListResponseMultiError is an error wrapping multiple validation errors
// returned by BookListResponse.ValidateAll() if the designated constraints
// aren't met.
type BookListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookListResponseMultiError) AllErrors() []error { return m }

// BookListResponseValidationError is the validation error returned by
// BookListResponse.Validate if the designated constraints aren't met.
type BookListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookListResponseValidationError) ErrorName() string { return "BookListResponseValidationError" }

// Error satisfies the builtin error interface
func (e BookListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookListResponseValidationError{}

// Validate checks the field values on BookListRequest_CursorPagination with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *BookListRequest_CursorPagination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookListRequest_CursorPagination with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// BookListRequest_CursorPaginationMultiError, or nil if none found.
func (m *BookListRequest_CursorPagination) ValidateAll() error {
	return m.validate(true)
}

func (m *BookListRequest_CursorPagination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Cursor

	if _, ok := _BookListRequest_CursorPagination_PageSize_InLookup[m.GetPageSize()]; !ok {
		err := BookListRequest_CursorPaginationValidationError{
			field:  "PageSize",
			reason: "value must be in list [2 10 50]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _BookListRequest_CursorPagination_SortBy_InLookup[m.GetSortBy()]; !ok {
		err := BookListRequest_CursorPaginationValidationError{
			field:  "SortBy",
			reason: "value must be in list [id title year]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _BookListRequest_CursorPagination_SortOrder_InLookup[m.GetSortOrder()]; !ok {
		err := BookListRequest_CursorPaginationValidationError{
			field:  "SortOrder",
			reason: "value must be in list [asc desc]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BookListRequest_CursorPaginationMultiError(errors)
	}

	return nil
}

// BookListRequest_CursorPaginationMultiError is an error wrapping multiple
// validation errors returned by
// BookListRequest_CursorPagination.ValidateAll() if the designated
// constraints aren't met.
type BookListRequest_CursorPaginationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookListRequest_CursorPaginationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookListRequest_CursorPaginationMultiError) AllErrors() []error { return m }

// BookListRequest_CursorPaginationValidationError is the validation error
// returned by BookListRequest_CursorPagination.Validate if the designated
// constraints aren't met.
type BookListRequest_CursorPaginationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookListRequest_CursorPaginationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookListRequest_CursorPaginationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookListRequest_CursorPaginationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookListRequest_CursorPaginationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookListRequest_CursorPaginationValidationError) ErrorName() string {
	return "BookListRequest_CursorPaginationValidationError"
}

// Error satisfies the builtin error interface
func (e BookListRequest_CursorPaginationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookListRequest_CursorPagination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookListRequest_CursorPaginationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookListRequest_CursorPaginationValidationError{}

var _BookListRequest_CursorPagination_PageSize_InLookup = map[uint64]struct{}{
	2:  {},
	10: {},
	50: {},
}

var _BookListRequest_CursorPagination_SortBy_InLookup = map[string]struct{}{
	"id":    {},
	"title": {},
	"year":  {},
}

var _BookListRequest_CursorPagination_SortOrder_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

// Validate checks the field values on BookListResponse_CursorPagination with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *BookListResponse_CursorPagination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookListResponse_CursorPagination
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// BookListResponse_CursorPaginationMultiError, or nil if none found.
func (m *BookListResponse_CursorPagination) ValidateAll() error {
	return m.validate(true)
}

func (m *BookListResponse_CursorPagination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCursorNext()) < 1 {
		err := BookListResponse_CursorPaginationValidationError{
			field:  "CursorNext",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BookListResponse_CursorPaginationMultiError(errors)
	}

	return nil
}

// BookListResponse_CursorPaginationMultiError is an error wrapping multiple
// validation errors returned by
// BookListResponse_CursorPagination.ValidateAll() if the designated
// constraints aren't met.
type BookListResponse_CursorPaginationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookListResponse_CursorPaginationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookListResponse_CursorPaginationMultiError) AllErrors() []error { return m }

// BookListResponse_CursorPaginationValidationError is the validation error
// returned by BookListResponse_CursorPagination.Validate if the designated
// constraints aren't met.
type BookListResponse_CursorPaginationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookListResponse_CursorPaginationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookListResponse_CursorPaginationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookListResponse_CursorPaginationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookListResponse_CursorPaginationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookListResponse_CursorPaginationValidationError) ErrorName() string {
	return "BookListResponse_CursorPaginationValidationError"
}

// Error satisfies the builtin error interface
func (e BookListResponse_CursorPaginationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookListResponse_CursorPagination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookListResponse_CursorPaginationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookListResponse_CursorPaginationValidationError{}
