// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: v1/book.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=Year,proto3" json:"Year,omitempty"`
	Genre         string                 `protobuf:"bytes,5,opt,name=Genre,proto3" json:"Genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type BookGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        []int64                `protobuf:"varint,1,rep,packed,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookGetRequest) Reset() {
	*x = BookGetRequest{}
	mi := &file_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookGetRequest) ProtoMessage() {}

func (x *BookGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookGetRequest.ProtoReflect.Descriptor instead.
func (*BookGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookGetRequest) GetBookId() []int64 {
	if x != nil {
		return x.BookId
	}
	return nil
}

type BookAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookAddRequest) Reset() {
	*x = BookAddRequest{}
	mi := &file_v1_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAddRequest) ProtoMessage() {}

func (x *BookAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAddRequest.ProtoReflect.Descriptor instead.
func (*BookAddRequest) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{2}
}

func (x *BookAddRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookAddRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookAddRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BookAddRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type BookListRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Pagination    *BookListRequest_CursorPagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListRequest) Reset() {
	*x = BookListRequest{}
	mi := &file_v1_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListRequest) ProtoMessage() {}

func (x *BookListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListRequest.ProtoReflect.Descriptor instead.
func (*BookListRequest) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{3}
}

func (x *BookListRequest) GetPagination() *BookListRequest_CursorPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type BooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          []*Book                `protobuf:"bytes,1,rep,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksResponse) Reset() {
	*x = BooksResponse{}
	mi := &file_v1_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksResponse) ProtoMessage() {}

func (x *BooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksResponse.ProtoReflect.Descriptor instead.
func (*BooksResponse) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{4}
}

func (x *BooksResponse) GetBook() []*Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type BookListResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Pagination    *BookListResponse_CursorPagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Books         []*Book                            `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListResponse) Reset() {
	*x = BookListResponse{}
	mi := &file_v1_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResponse) ProtoMessage() {}

func (x *BookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResponse.ProtoReflect.Descriptor instead.
func (*BookListResponse) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{5}
}

func (x *BookListResponse) GetPagination() *BookListResponse_CursorPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *BookListResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type BookListRequest_CursorPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListRequest_CursorPagination) Reset() {
	*x = BookListRequest_CursorPagination{}
	mi := &file_v1_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListRequest_CursorPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListRequest_CursorPagination) ProtoMessage() {}

func (x *BookListRequest_CursorPagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListRequest_CursorPagination.ProtoReflect.Descriptor instead.
func (*BookListRequest_CursorPagination) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BookListRequest_CursorPagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *BookListRequest_CursorPagination) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BookListRequest_CursorPagination) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *BookListRequest_CursorPagination) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type BookListResponse_CursorPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CursorNext    string                 `protobuf:"bytes,1,opt,name=cursorNext,proto3" json:"cursorNext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListResponse_CursorPagination) Reset() {
	*x = BookListResponse_CursorPagination{}
	mi := &file_v1_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListResponse_CursorPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResponse_CursorPagination) ProtoMessage() {}

func (x *BookListResponse_CursorPagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResponse_CursorPagination.ProtoReflect.Descriptor instead.
func (*BookListResponse_CursorPagination) Descriptor() ([]byte, []int) {
	return file_v1_book_proto_rawDescGZIP(), []int{5, 0}
}

func (x *BookListResponse_CursorPagination) GetCursorNext() string {
	if x != nil {
		return x.CursorNext
	}
	return ""
}

var File_v1_book_proto protoreflect.FileDescriptor

const file_v1_book_proto_rawDesc = "" +
	"\n" +
	"\rv1/book.proto\x12\x0fmathbdw.grpc.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa0\x02\n" +
	"\x04Book\x12*\n" +
	"\x02id\x18\x01 \x01(\x03B\x1a\x92A\x172\x12Identificator BookJ\x011R\x02id\x121\n" +
	"\x05Title\x18\x02 \x01(\tB\x1b\x92A\x182\n" +
	"Book titleJ\n" +
	"\"The Book\"R\x05Title\x12H\n" +
	"\vDescription\x18\x03 \x01(\tB&\x92A#2\vDescriptionJ\x14\"The Book Adventure\"R\vDescription\x128\n" +
	"\x04Year\x18\x04 \x01(\x05B$\x92A!2\x19Year the book was writtenJ\x042000R\x04Year\x125\n" +
	"\x05Genre\x18\x05 \x01(\tB\x1f\x92A\x1c2\rGenre of bookJ\v\"Adventure\"R\x05Genre\"o\n" +
	"\x0eBookGetRequest\x12]\n" +
	"\abook_id\x18\x01 \x03(\x03BD\x92A-2$Slice identificators. Unique params.J\x05[1,2]\xfaB\x11\x92\x01\x0e\b\x01\x10\n" +
	"\x18\x01\"\x04\"\x02(\x01(\x00R\x06bookId\"\x94\x02\n" +
	"\x0eBookAddRequest\x12;\n" +
	"\x05title\x18\x01 \x01(\tB%\x92A\x182\x0eTitle the bookJ\x06\"Book\"\xfaB\ar\x05\x10\x02\x18\x80\x01R\x05title\x12Q\n" +
	"\vdescription\x18\x02 \x01(\tB/\x92A%2\x14Description the bookJ\r\"Description\"\xfaB\x04r\x02\x10\x02R\vdescription\x123\n" +
	"\x04year\x18\x03 \x01(\x05B\x1f\x92A\x152\rYear the bookJ\x042000\xfaB\x04\x1a\x02(\x01R\x04year\x12=\n" +
	"\x05genre\x18\x04 \x01(\tB'\x92A\x1d2\x0eGenre the bookJ\v\"Adventure\"\xfaB\x04r\x02\x10\x02R\x05genre\"\xb1\x03\n" +
	"\x0fBookListRequest\x12y\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v21.mathbdw.grpc.v1.BookListRequest.CursorPaginationB&\x92A\x1b2\x19map params for pagination\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"pagination\x1a\xa2\x02\n" +
	"\x10CursorPagination\x126\n" +
	"\x06cursor\x18\x01 \x01(\tB\x1e\x92A\x1b2\rString cursorJ\n" +
	"\"qwefszvs\"R\x06cursor\x12A\n" +
	"\tpage_size\x18\x02 \x01(\x04B$\x92A\x162\x11Size rows on pageJ\x012\xfaB\b2\x060\x020\n" +
	"02R\bpageSize\x12I\n" +
	"\asort_by\x18\x03 \x01(\tB0\x92A\x172\rSorting fieldJ\x06\"year\"\xfaB\x13r\x11R\x02idR\x05titleR\x04yearR\x06sortBy\x12H\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tB)\x92A\x162\rSorting orderJ\x05\"asc\"\xfaB\rr\vR\x03ascR\x04descR\tsortOrder\"L\n" +
	"\rBooksResponse\x12;\n" +
	"\x04book\x18\x01 \x03(\v2\x15.mathbdw.grpc.v1.BookB\x10\x92A\r2\vArray booksR\x04book\"\xe9\x01\n" +
	"\x10BookListResponse\x12R\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v22.mathbdw.grpc.v1.BookListResponse.CursorPaginationR\n" +
	"pagination\x12+\n" +
	"\x05books\x18\x02 \x03(\v2\x15.mathbdw.grpc.v1.BookR\x05books\x1aT\n" +
	"\x10CursorPagination\x12@\n" +
	"\n" +
	"cursorNext\x18\x01 \x01(\tB \x92A\x162\rSorting orderJ\x05\"asc\"\xfaB\x04r\x02\x10\x01R\n" +
	"cursorNext2\xe8\x05\n" +
	"\vBookService\x12\x89\x02\n" +
	"\bGetByIDs\x12\x1f.mathbdw.grpc.v1.BookGetRequest\x1a\x1e.mathbdw.grpc.v1.BooksResponse\"\xbb\x01\x92A\xa6\x01\n" +
	"\x05books\x12\x10Get books by IDs\x1a\x8a\x01Get books by their IDs\n" +
	"\n" +
	"### Custom Headers:\n" +
	"- **X-Request-ID**: Unique request identifier\n" +
	"- **X-Upload-Token**: Upload authorization token\x82\xd3\xe4\x93\x02\v\x12\t/v1/books\x12\x92\x01\n" +
	"\x03Add\x12\x1f.mathbdw.grpc.v1.BookAddRequest\x1a\x16.google.protobuf.Empty\"R\x92A;\n" +
	"\x05books\x12\x11Create a new book\x1a\x1fCreate a new book in the system\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/books\x12\xab\x01\n" +
	"\x04List\x12 .mathbdw.grpc.v1.BookListRequest\x1a!.mathbdw.grpc.v1.BookListResponse\"^\x92AF\n" +
	"\x05books\x12\x1bList of books on pagination\x1a Returns a list of books by pages\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/book-list\x12\x89\x01\n" +
	"\x06Delete\x12\x1f.mathbdw.grpc.v1.BookGetRequest\x1a\x16.google.protobuf.Empty\"F\x92A2\n" +
	"\x05books\x12\x13Delete books by IDs\x1a\x14Deletes books by IDs\x82\xd3\xe4\x93\x02\v*\t/v1/booksB\x91\x02\x92A\xee\x01\x12\x85\x01\n" +
	"\x10Book Service API\x12'API for book management with OpenAPI v3\"C\n" +
	"\vAPI Support\x12\x1fhttps://github.com/mathbdw/book\x1a\x13support@example.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ<\n" +
	":\n" +
	"\x06bearer\x120\b\x02\x12\x1bBearer token authentication\x1a\rAuthorization \x02Z\x1dgithub.com/mathbdw/book/protob\x06proto3"

var (
	file_v1_book_proto_rawDescOnce sync.Once
	file_v1_book_proto_rawDescData []byte
)

func file_v1_book_proto_rawDescGZIP() []byte {
	file_v1_book_proto_rawDescOnce.Do(func() {
		file_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_book_proto_rawDesc), len(file_v1_book_proto_rawDesc)))
	})
	return file_v1_book_proto_rawDescData
}

var file_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_book_proto_goTypes = []any{
	(*Book)(nil),                              // 0: mathbdw.grpc.v1.Book
	(*BookGetRequest)(nil),                    // 1: mathbdw.grpc.v1.BookGetRequest
	(*BookAddRequest)(nil),                    // 2: mathbdw.grpc.v1.BookAddRequest
	(*BookListRequest)(nil),                   // 3: mathbdw.grpc.v1.BookListRequest
	(*BooksResponse)(nil),                     // 4: mathbdw.grpc.v1.BooksResponse
	(*BookListResponse)(nil),                  // 5: mathbdw.grpc.v1.BookListResponse
	(*BookListRequest_CursorPagination)(nil),  // 6: mathbdw.grpc.v1.BookListRequest.CursorPagination
	(*BookListResponse_CursorPagination)(nil), // 7: mathbdw.grpc.v1.BookListResponse.CursorPagination
	(*empty.Empty)(nil),                       // 8: google.protobuf.Empty
}
var file_v1_book_proto_depIdxs = []int32{
	6, // 0: mathbdw.grpc.v1.BookListRequest.pagination:type_name -> mathbdw.grpc.v1.BookListRequest.CursorPagination
	0, // 1: mathbdw.grpc.v1.BooksResponse.book:type_name -> mathbdw.grpc.v1.Book
	7, // 2: mathbdw.grpc.v1.BookListResponse.pagination:type_name -> mathbdw.grpc.v1.BookListResponse.CursorPagination
	0, // 3: mathbdw.grpc.v1.BookListResponse.books:type_name -> mathbdw.grpc.v1.Book
	1, // 4: mathbdw.grpc.v1.BookService.GetByIDs:input_type -> mathbdw.grpc.v1.BookGetRequest
	2, // 5: mathbdw.grpc.v1.BookService.Add:input_type -> mathbdw.grpc.v1.BookAddRequest
	3, // 6: mathbdw.grpc.v1.BookService.List:input_type -> mathbdw.grpc.v1.BookListRequest
	1, // 7: mathbdw.grpc.v1.BookService.Delete:input_type -> mathbdw.grpc.v1.BookGetRequest
	4, // 8: mathbdw.grpc.v1.BookService.GetByIDs:output_type -> mathbdw.grpc.v1.BooksResponse
	8, // 9: mathbdw.grpc.v1.BookService.Add:output_type -> google.protobuf.Empty
	5, // 10: mathbdw.grpc.v1.BookService.List:output_type -> mathbdw.grpc.v1.BookListResponse
	8, // 11: mathbdw.grpc.v1.BookService.Delete:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_book_proto_init() }
func file_v1_book_proto_init() {
	if File_v1_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_book_proto_rawDesc), len(file_v1_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_book_proto_goTypes,
		DependencyIndexes: file_v1_book_proto_depIdxs,
		MessageInfos:      file_v1_book_proto_msgTypes,
	}.Build()
	File_v1_book_proto = out.File
	file_v1_book_proto_goTypes = nil
	file_v1_book_proto_depIdxs = nil
}
