// Code generated by MockGen. DO NOT EDIT.
// Source: ./metric.go
//
// Generated by this command:
//
//	mockgen -destination=./../../../mocks/mock_metric.go -package=mocks -source=./metric.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandlersMetrics is a mock of HandlersMetrics interface.
type MockHandlersMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMetricsMockRecorder
	isgomock struct{}
}

// MockHandlersMetricsMockRecorder is the mock recorder for MockHandlersMetrics.
type MockHandlersMetricsMockRecorder struct {
	mock *MockHandlersMetrics
}

// NewMockHandlersMetrics creates a new mock instance.
func NewMockHandlersMetrics(ctrl *gomock.Controller) *MockHandlersMetrics {
	mock := &MockHandlersMetrics{ctrl: ctrl}
	mock.recorder = &MockHandlersMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlersMetrics) EXPECT() *MockHandlersMetricsMockRecorder {
	return m.recorder
}

// RecordHanderRequest mocks base method.
func (m *MockHandlersMetrics) RecordHanderRequest(ctx context.Context, method, path string, statusCode int, duration float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHanderRequest", ctx, method, path, statusCode, duration)
}

// RecordHanderRequest indicates an expected call of RecordHanderRequest.
func (mr *MockHandlersMetricsMockRecorder) RecordHanderRequest(ctx, method, path, statusCode, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHanderRequest", reflect.TypeOf((*MockHandlersMetrics)(nil).RecordHanderRequest), ctx, method, path, statusCode, duration)
}

// MockUsecasesMetrics is a mock of UsecasesMetrics interface.
type MockUsecasesMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockUsecasesMetricsMockRecorder
	isgomock struct{}
}

// MockUsecasesMetricsMockRecorder is the mock recorder for MockUsecasesMetrics.
type MockUsecasesMetricsMockRecorder struct {
	mock *MockUsecasesMetrics
}

// NewMockUsecasesMetrics creates a new mock instance.
func NewMockUsecasesMetrics(ctrl *gomock.Controller) *MockUsecasesMetrics {
	mock := &MockUsecasesMetrics{ctrl: ctrl}
	mock.recorder = &MockUsecasesMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecasesMetrics) EXPECT() *MockUsecasesMetricsMockRecorder {
	return m.recorder
}

// RecordBookCreated mocks base method.
func (m *MockUsecasesMetrics) RecordBookCreated(ctx context.Context, genre string, duration float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordBookCreated", ctx, genre, duration)
}

// RecordBookCreated indicates an expected call of RecordBookCreated.
func (mr *MockUsecasesMetricsMockRecorder) RecordBookCreated(ctx, genre, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBookCreated", reflect.TypeOf((*MockUsecasesMetrics)(nil).RecordBookCreated), ctx, genre, duration)
}

// MockRepositoriesMetrics is a mock of RepositoriesMetrics interface.
type MockRepositoriesMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoriesMetricsMockRecorder
	isgomock struct{}
}

// MockRepositoriesMetricsMockRecorder is the mock recorder for MockRepositoriesMetrics.
type MockRepositoriesMetricsMockRecorder struct {
	mock *MockRepositoriesMetrics
}

// NewMockRepositoriesMetrics creates a new mock instance.
func NewMockRepositoriesMetrics(ctrl *gomock.Controller) *MockRepositoriesMetrics {
	mock := &MockRepositoriesMetrics{ctrl: ctrl}
	mock.recorder = &MockRepositoriesMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoriesMetrics) EXPECT() *MockRepositoriesMetricsMockRecorder {
	return m.recorder
}

// RecordDatabaseQuery mocks base method.
func (m *MockRepositoriesMetrics) RecordDatabaseQuery(ctx context.Context, operation, table string, duration float64, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDatabaseQuery", ctx, operation, table, duration, success)
}

// RecordDatabaseQuery indicates an expected call of RecordDatabaseQuery.
func (mr *MockRepositoriesMetricsMockRecorder) RecordDatabaseQuery(ctx, operation, table, duration, success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDatabaseQuery", reflect.TypeOf((*MockRepositoriesMetrics)(nil).RecordDatabaseQuery), ctx, operation, table, duration, success)
}
