// Code generated by MockGen. DO NOT EDIT.
// Source: ./book_event_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./../../../mocks/mock_book_event_repository.go -package=mocks -source=./book_event_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/mathbdw/book/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockBookEventRepository is a mock of BookEventRepository interface.
type MockBookEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookEventRepositoryMockRecorder
	isgomock struct{}
}

// MockBookEventRepositoryMockRecorder is the mock recorder for MockBookEventRepository.
type MockBookEventRepositoryMockRecorder struct {
	mock *MockBookEventRepository
}

// NewMockBookEventRepository creates a new mock instance.
func NewMockBookEventRepository(ctrl *gomock.Controller) *MockBookEventRepository {
	mock := &MockBookEventRepository{ctrl: ctrl}
	mock.recorder = &MockBookEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookEventRepository) EXPECT() *MockBookEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookEventRepository) Create(ctx context.Context, bookEvent entities.BookEvent) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, bookEvent)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookEventRepositoryMockRecorder) Create(ctx, bookEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookEventRepository)(nil).Create), ctx, bookEvent)
}

// Lock mocks base method.
func (m *MockBookEventRepository) Lock(ctx context.Context, batchSize uint64) ([]entities.BookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, batchSize)
	ret0, _ := ret[0].([]entities.BookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *MockBookEventRepositoryMockRecorder) Lock(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockBookEventRepository)(nil).Lock), ctx, batchSize)
}

// Remove mocks base method.
func (m *MockBookEventRepository) Remove(ctx context.Context, eventIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, eventIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockBookEventRepositoryMockRecorder) Remove(ctx, eventIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockBookEventRepository)(nil).Remove), ctx, eventIDs)
}

// Unlock mocks base method.
func (m *MockBookEventRepository) Unlock(ctx context.Context, eventIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, eventIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockBookEventRepositoryMockRecorder) Unlock(ctx, eventIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockBookEventRepository)(nil).Unlock), ctx, eventIDs)
}
