// Code generated by MockGen. DO NOT EDIT.
// Source: ./observability.go
//
// Generated by this command:
//
//	mockgen -destination=./../../../mocks/mock_observability.go -package=mocks -source=./observability.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/mathbdw/book/internal/interfaces/observability"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlerObservability is a mock of HandlerObservability interface.
type MockHandlerObservability struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerObservabilityMockRecorder
	isgomock struct{}
}

// MockHandlerObservabilityMockRecorder is the mock recorder for MockHandlerObservability.
type MockHandlerObservabilityMockRecorder struct {
	mock *MockHandlerObservability
}

// NewMockHandlerObservability creates a new mock instance.
func NewMockHandlerObservability(ctrl *gomock.Controller) *MockHandlerObservability {
	mock := &MockHandlerObservability{ctrl: ctrl}
	mock.recorder = &MockHandlerObservabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerObservability) EXPECT() *MockHandlerObservabilityMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockHandlerObservability) Debug(msg string, fields interfaces.Field) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", msg, fields)
}

// Debug indicates an expected call of Debug.
func (mr *MockHandlerObservabilityMockRecorder) Debug(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockHandlerObservability)(nil).Debug), msg, fields)
}

// Error mocks base method.
func (m *MockHandlerObservability) Error(msg string, fields interfaces.Field) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg, fields)
}

// Error indicates an expected call of Error.
func (mr *MockHandlerObservabilityMockRecorder) Error(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockHandlerObservability)(nil).Error), msg, fields)
}

// Fatal mocks base method.
func (m *MockHandlerObservability) Fatal(msg string, fields interfaces.Field) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", msg, fields)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockHandlerObservabilityMockRecorder) Fatal(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockHandlerObservability)(nil).Fatal), msg, fields)
}

// Info mocks base method.
func (m *MockHandlerObservability) Info(msg string, fields interfaces.Field) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg, fields)
}

// Info indicates an expected call of Info.
func (mr *MockHandlerObservabilityMockRecorder) Info(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockHandlerObservability)(nil).Info), msg, fields)
}

// RecordHanderRequest mocks base method.
func (m *MockHandlerObservability) RecordHanderRequest(ctx context.Context, method, path string, statusCode int, duration float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHanderRequest", ctx, method, path, statusCode, duration)
}

// RecordHanderRequest indicates an expected call of RecordHanderRequest.
func (mr *MockHandlerObservabilityMockRecorder) RecordHanderRequest(ctx, method, path, statusCode, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHanderRequest", reflect.TypeOf((*MockHandlerObservability)(nil).RecordHanderRequest), ctx, method, path, statusCode, duration)
}

// SetLevel mocks base method.
func (m *MockHandlerObservability) SetLevel(newLevel int8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLevel", newLevel)
}

// SetLevel indicates an expected call of SetLevel.
func (mr *MockHandlerObservabilityMockRecorder) SetLevel(newLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLevel", reflect.TypeOf((*MockHandlerObservability)(nil).SetLevel), newLevel)
}

// StartSpan mocks base method.
func (m *MockHandlerObservability) StartSpan(ctx context.Context, name string) (context.Context, interfaces.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(interfaces.Span)
	return ret0, ret1
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockHandlerObservabilityMockRecorder) StartSpan(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockHandlerObservability)(nil).StartSpan), ctx, name)
}

// Warn mocks base method.
func (m *MockHandlerObservability) Warn(msg string, fields interfaces.Field) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", msg, fields)
}

// Warn indicates an expected call of Warn.
func (mr *MockHandlerObservabilityMockRecorder) Warn(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockHandlerObservability)(nil).Warn), msg, fields)
}

// WithContext mocks base method.
func (m *MockHandlerObservability) WithContext(ctx context.Context) interfaces.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(interfaces.Logger)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockHandlerObservabilityMockRecorder) WithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockHandlerObservability)(nil).WithContext), ctx)
}

// MockUsecaseObservability is a mock of UsecaseObservability interface.
type MockUsecaseObservability struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseObservabilityMockRecorder
	isgomock struct{}
}

// MockUsecaseObservabilityMockRecorder is the mock recorder for MockUsecaseObservability.
type MockUsecaseObservabilityMockRecorder struct {
	mock *MockUsecaseObservability
}

// NewMockUsecaseObservability creates a new mock instance.
func NewMockUsecaseObservability(ctrl *gomock.Controller) *MockUsecaseObservability {
	mock := &MockUsecaseObservability{ctrl: ctrl}
	mock.recorder = &MockUsecaseObservabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecaseObservability) EXPECT() *MockUsecaseObservabilityMockRecorder {
	return m.recorder
}

// RecordBookCreated mocks base method.
func (m *MockUsecaseObservability) RecordBookCreated(ctx context.Context, genre string, duration float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordBookCreated", ctx, genre, duration)
}

// RecordBookCreated indicates an expected call of RecordBookCreated.
func (mr *MockUsecaseObservabilityMockRecorder) RecordBookCreated(ctx, genre, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBookCreated", reflect.TypeOf((*MockUsecaseObservability)(nil).RecordBookCreated), ctx, genre, duration)
}

// StartSpan mocks base method.
func (m *MockUsecaseObservability) StartSpan(ctx context.Context, name string) (context.Context, interfaces.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(interfaces.Span)
	return ret0, ret1
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockUsecaseObservabilityMockRecorder) StartSpan(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockUsecaseObservability)(nil).StartSpan), ctx, name)
}

// MockRepositoryObservability is a mock of RepositoryObservability interface.
type MockRepositoryObservability struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryObservabilityMockRecorder
	isgomock struct{}
}

// MockRepositoryObservabilityMockRecorder is the mock recorder for MockRepositoryObservability.
type MockRepositoryObservabilityMockRecorder struct {
	mock *MockRepositoryObservability
}

// NewMockRepositoryObservability creates a new mock instance.
func NewMockRepositoryObservability(ctrl *gomock.Controller) *MockRepositoryObservability {
	mock := &MockRepositoryObservability{ctrl: ctrl}
	mock.recorder = &MockRepositoryObservabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryObservability) EXPECT() *MockRepositoryObservabilityMockRecorder {
	return m.recorder
}

// RecordDatabaseQuery mocks base method.
func (m *MockRepositoryObservability) RecordDatabaseQuery(ctx context.Context, operation, table string, duration float64, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDatabaseQuery", ctx, operation, table, duration, success)
}

// RecordDatabaseQuery indicates an expected call of RecordDatabaseQuery.
func (mr *MockRepositoryObservabilityMockRecorder) RecordDatabaseQuery(ctx, operation, table, duration, success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDatabaseQuery", reflect.TypeOf((*MockRepositoryObservability)(nil).RecordDatabaseQuery), ctx, operation, table, duration, success)
}

// StartSpan mocks base method.
func (m *MockRepositoryObservability) StartSpan(ctx context.Context, name string) (context.Context, interfaces.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(interfaces.Span)
	return ret0, ret1
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockRepositoryObservabilityMockRecorder) StartSpan(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockRepositoryObservability)(nil).StartSpan), ctx, name)
}
